#!/bin/bash

cargo build --release
touch rust.txt

for elements in 100000 1000000 2000000 9000000 10000000 2600000000; do
  echo '' >> rust.txt
  for threads in  8  7  6  5  4  3  2  1; do
    echo "$elements $threads" >> rust.txt
    ./target/release/heapsort $elements $threads false >> rust.txt
  done
done



